# Generated by Django 3.2.7 on 2021-11-07 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='VIP_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='VIP until'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='Authorship Status'),
        ),
    ]
