# Generated by Django 3.2.7 on 2022-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_VIP',
            field=models.BooleanField(default=False, verbose_name='VIP?'),
        ),
    ]
