# Generated by Django 3.2.7 on 2022-08-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220822_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'IP Address', 'verbose_name_plural': 'IP Addresses'},
        ),
    ]
