# Generated by Django 3.2.7 on 2022-02-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_VIP',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
    ]
